name: flutter_security
description: A flutter package that aim to take care of your mobile app security side.
version: 0.1.6
homepage: https://github.com/marcotrumpet/flutter_security

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable:
  json_annotation:
  freezed_annotation: 
  encrypt: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  freezed: 

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter_security
        pluginClass: FlutterSecurityPlugin
      ios:
        pluginClass: FlutterSecurityPlugin